/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/patient/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 환자 최초 등록
         * @description 의료진이 D0에서 발급한 8자리 등록 코드(예: K7M3X9P2)와 환자가 설정할
         *     6자리 PIN으로 환자 계정을 활성화. 등록 코드는 1회용.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example K7M3X9P2 */
                        registration_code: string;
                        /** @example 482917 */
                        pin: string;
                    };
                };
            };
            responses: {
                /** @description 등록 성공, Access Token 발급(24시간) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description 등록 코드 없음 또는 이미 사용됨 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 등록 코드 만료 (7일 경과) */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/patient/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 환자 로그인
         * @description Access Token 만료(24h) 또는 앱 재실행 시 등록 코드 + PIN으로 재로그인.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        registration_code: string;
                        pin: string;
                    };
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description 등록 코드 또는 PIN 불일치 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/provider/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 의료진 로그인 (이메일·비밀번호) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 로그인 성공, Access Token 발급(8시간) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenResponse"];
                    };
                };
                /** @description 자격 증명 불일치 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 클라이언트가 Access Token 폐기 신호. v3.0은 서버 측 token blacklist를
         *     운영하지 않으므로 실제로는 토큰을 폐기하지 않음. 클라이언트가 토큰을 삭제.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 로그아웃 처리됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/patient/pin/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 환자 PIN 변경 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        current_pin: string;
                        new_pin: string;
                    };
                };
            };
            responses: {
                /** @description PIN 변경 성공 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 현재 PIN 불일치 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * P1 홈 화면 통합 응답
         * @description 환자 본인의 홈 화면 정보를 한 번에 조회. 단주 일수, 현재 Week,
         *     다음 세션까지 남은 일수, 오늘 할 일, 다음 외래(next_outpatient_date),
         *     LLM 잠금 상태(llm_locked) 등.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PatientHomeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 체크인 목록 조회 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 페이지네이션 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            items?: components["schemas"]["Checkin"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 오늘 체크인 제출 (하루 1회) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckinSubmit"];
                };
            };
            responses: {
                /** @description 제출 성공. safety_classification에 위험 시 grade/event_type/next_action 포함. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckinResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                /** @description CHECKIN_ALREADY_SUBMITTED — 오늘 이미 체크인함 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/checkins/{checkin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 체크인 단건 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    checkin_id: components["parameters"]["CheckinId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Checkin"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 같은 날 체크인 수정 (24시간 이내) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    checkin_id: components["parameters"]["CheckinId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckinPatch"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckinResponse"];
                    };
                };
                /** @description 수정 시간 초과 (24h) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/conversations/current-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 진행 중 또는 다음 세션 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentSessionInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/conversations/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 새 CBT 세션 시작
         * @description 한 시점에 한 세션만 활성화 가능.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 세션 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                /** @description 이미 진행 중인 세션이 있음 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description SAFETY_LOCKED — 안전 이벤트로 LLM 대화 잠금 상태 */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/conversations/craving": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 갈망 대화 시작
         * @description 횟수·시간 제한 없음. 세션과 별도 컨텍스트.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 갈망 대화 시작 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                /** @description SAFETY_LOCKED */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대화 이력 조회 (페이지네이션)
         * @description 앱 재시작 후 화면 복구용.
         */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    conversation_id: components["parameters"]["ConversationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 페이지네이션 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            items?: components["schemas"]["Message"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 환자 메시지 전송 + LLM 응답 SSE 스트리밍
         * @description 응답은 text/event-stream (SSE).
         *
         *     정상 흐름: `start` → `token` (반복) → `done`
         *
         *     등급 A 감지: `safety_classified(grade=A)` → `done(safety_locked)`
         *
         *     등급 B 감지: `safety_classified(grade=B)` → `context_switched` →
         *     `start` → `token` (반복) → `done`
         *
         *     v3.0에서 백엔드는 등급 A 발생 후에도 강제로 423을 반환하지 않을 수 있음.
         *     SafetyEvent 기록 및 llm_locked 상태 노출만 수행하며, 클라이언트(환자 앱)가
         *     시간 기반(24시간) 또는 사용자의 명시적 확인(P4 '다시 시작하기' 탭)으로
         *     잠금 처리.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: components["parameters"]["ConversationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                        /**
                         * Format: uuid
                         * @description 클라이언트 측 멱등성 키 (선택)
                         */
                        client_message_id?: string;
                    };
                };
            };
            responses: {
                /** @description SSE 스트리밍 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description SAFETY_LOCKED — 잠금 상태 (v3.0에서는 약화, 클라이언트 측 처리) */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/conversations/{conversation_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 대화 명시적 종료 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: components["parameters"]["ConversationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        reason: "completed" | "abandoned_by_user" | "timeout";
                    };
                };
            };
            responses: {
                /** @description 종료 처리됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            ended_at?: string;
                            reason?: string;
                            /** Format: date-time */
                            next_session_available_at?: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/safety/p4-shown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** P4 응급 안내 노출 기록 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        trigger: "auto_safety_event" | "manual_button";
                        related_safety_event_id?: string | null;
                        /** @enum {string|null} */
                        clicked_resource?: "1393" | "119" | "sso" | "none" | null;
                    };
                };
            };
            responses: {
                /** @description 기록 완료 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            p4_event_id?: string;
                            /** Format: date-time */
                            shown_at?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/safety/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 본인 안전 이벤트 이력 조회 */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 페이지네이션 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            items?: components["schemas"]["SafetyEvent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 단주 일수·세션 진행률 조회 (v3.0 단순) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sobriety_days?: number;
                            weeks_completed?: number;
                            current_week?: number;
                            /** Format: date */
                            next_session_date?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 설정 조회 (알림 시각·세션 요일·SSO) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 설정 부분 수정 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsPatch"];
                };
            };
            responses: {
                /** @description 수정 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/sso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SSO 추가·수정 (1명 한도, 추가 시 교체) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupportPersonInput"];
                };
            };
            responses: {
                /** @description SSO 저장됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupportPerson"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sso/{sso_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** SSO 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sso_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 삭제됨 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 의료진 본인 프로필 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            provider_id?: string;
                            name?: string;
                            /** Format: email */
                            email?: string;
                            affiliation?: string;
                            active_patient_count?: number;
                            /** @description v3.0에서 의료진 자동 알림은 없으나 향후 확장 대비 유지. */
                            notification_preferences?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 담당 환자 목록 조회 (v3.0은 정렬·필터 제한) */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 페이지네이션 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedEnvelope"] & {
                            items?: components["schemas"]["PatientListItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** D0 환자 신규 등록 + DischargeProfile 동시 저장 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DischargeProfileInput"];
                };
            };
            responses: {
                /**
                 * @description 등록 성공. registration_code(8자리)를 환자에게 SMS·종이 등으로 전달.
                 *     primary_triggers는 내부 LLM이 normalized_triggers로 자동 변환.
                 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            patient_id?: string;
                            registration_code?: string;
                            /**
                             * Format: date-time
                             * @description 등록 코드 만료 시각 (7일 후)
                             */
                            expires_at?: string;
                            /**
                             * @example [
                             *       "work_stress",
                             *       "social_pressure"
                             *     ]
                             */
                            normalized_triggers?: string[];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/patients/{patient_id}/registration-code/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 등록 코드 분실·만료 시 재발급 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 새 등록 코드 발급됨 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            registration_code?: string;
                            /** Format: date-time */
                            expires_at?: string;
                        };
                    };
                };
                /** @description PATIENT_ALREADY_REGISTERED — 이미 환자가 등록 완료한 상태 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 환자 상세 대시보드 (통합 응답)
         * @description 외래 진료 시 5분 안에 환자 상태 파악용. v3.0에서는 모든 정보를
         *     이 응답 하나에 통합 (안전 이벤트·세션 이력·대화 로그·갈망 일지의 별도
         *     엔드포인트는 Post-MVP로 이동).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 환자 종합 정보 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PatientDetailDashboard"];
                    };
                };
                /** @description 담당 환자가 아님 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/patients/{patient_id}/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 처방 약물 전체 교체. 즉시 LLM 컨텍스트 반영. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        medications: components["schemas"]["Medication"][];
                        /** @description 변경 사유 (선택) */
                        change_note?: string;
                    };
                };
            };
            responses: {
                /** @description 갱신 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            patient_id?: string;
                            medications?: components["schemas"]["Medication"][];
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/patients/{patient_id}/next-outpatient-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 다음 외래 예약일 갱신
         * @description 외래 일정이 변경된 경우 의료진이 직접 갱신. 변경 즉시 환자 P1 홈에
         *     반영(GET /me/patient 응답의 next_outpatient_date).
         *     v3.0에서 의료진→환자 메시지 발송이 Post-MVP로 이동되었으므로, 일정
         *     변경 사실을 명시적으로 알려야 하는 경우 SMS·전화 등 앱 외 수단으로 보완.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        next_outpatient_date: string;
                        change_note?: string;
                    };
                };
            };
            responses: {
                /** @description 갱신 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            patient_id?: string;
                            /** Format: date */
                            next_outpatient_date?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
                /** @description VALIDATION_ERROR (과거 날짜 등) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/provider/patients/{patient_id}/program-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 프로그램 상태 변경
         * @description 환자가 사용 중단 요청을 직접 보낼 수단이 v3.0에 없으므로, 환자가
         *     사용을 그만두면 의료진이 외래에서 active → withdrawn으로 변경.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        new_status: "completed" | "withdrawn";
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description 상태 변경 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            patient_id?: string;
                            program_status?: string;
                            /** Format: date-time */
                            changed_at?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/internal/safety/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 환자 입력 안전 분류 (룰 + Haiku 4.5 LLM hybrid)
         * @description 5종 위험 신호(자살·급성중독·재발·복약중단·PAWS) 분류, 등급 A/B로 분리.
         *     Recall > Precision 정책.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SafetyClassifyRequest"];
                };
            };
            responses: {
                /** @description 분류 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafetyClassifyResponse"];
                    };
                };
                /** @description 분류기 LLM 일시 장애 시 룰 기반 결과만 반환 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SafetyClassifyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/stage/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 단계 판단기 — CBT 세션 5단계 진행 추적
         * @description 매 환자 발화 후 호출. Sonnet 4.6.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StageTrackRequest"];
                };
            };
            responses: {
                /** @description 추적 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StageTrackResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/session/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 세션 요약기 — 세션 종료 시 SessionSummary 생성
         * @description 다음 Week 세션 LLM 인계용 요약. Sonnet 4.6. 동기·비동기 모두 지원.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SessionSummarizeRequest"];
                };
            };
            responses: {
                /** @description 동기 응답 (async=false) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionSummary"];
                    };
                };
                /** @description 비동기 응답 (async=true), Job ID 반환 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            job_id?: string;
                            /** @enum {string} */
                            status?: "queued" | "processing";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/output/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 출력 검증 필터 (의학 어휘·AVE 2종)
         * @description LLM 출력 검증. v1.0 5종에서 v2.0 이후 2종으로 축소.
         *     Sycophancy·세션 표류·위기 부적절은 v2.0에서 제외.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                        conversation_context: components["schemas"]["ConversationContext"];
                        message_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description 검증 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OutputFilterResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/llm/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LLM 게이트웨이 — Anthropic API 호출 추상화
         * @description 키 관리·로깅·재시도·rate limiting을 게이트웨이가 일괄 처리.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LLMInvokeRequest"];
                };
            };
            responses: {
                /** @description stream=false 응답 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LLMInvokeResponse"];
                        "text/event-stream": string;
                    };
                };
                /** @description LLM_TOKEN_QUOTA_EXCEEDED — 환자별 일일 한도 초과 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description LLM_UPSTREAM_UNAVAILABLE — Anthropic API 장애 (retry_after_seconds 포함) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/llm/usage/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 환자별 일일 토큰 사용량 조회 (한도 체크용) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: components["parameters"]["PatientId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 사용량 정보 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date */
                            date?: string;
                            used_tokens?: number;
                            daily_quota?: number;
                            quota_remaining?: number;
                            breakdown_by_model?: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/context/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 컨텍스트 빌더 — Week N 시스템 프롬프트 + 환자 컨텍스트 조립 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patient_id: string;
                        context_type: components["schemas"]["ConversationContext"];
                        /** @description context_type=session인 경우 필수 */
                        week_number?: number;
                    };
                };
            };
            responses: {
                /** @description 조립된 프롬프트 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            system_prompt?: string;
                            /**
                             * @description 디버깅용. discharge_profile_summary, previous_session_summary,
                             *     recent_checkins_summary 등.
                             */
                            context_blocks?: Record<string, never>;
                            /** @description git commit hash 등 */
                            prompt_version?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/trigger/normalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** D0 음주 트리거 자유 텍스트 → 정규화 태그 (Haiku 4.5) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        raw_text: string;
                    };
                };
            };
            responses: {
                /** @description 정규화 결과 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @example [
                             *       "work_stress",
                             *       "social_pressure",
                             *       "loneliness"
                             *     ]
                             */
                            normalized_tags?: string[];
                            /** Format: float */
                            confidence?: number;
                            reasoning?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 백엔드 컴포넌트 상태 확인 (모니터링용, 인증 없음) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 헬스 상태 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            overall_status?: "healthy" | "degraded" | "unhealthy";
                            components?: {
                                /** @example safety_classifier */
                                name?: string;
                                /** @enum {string} */
                                status?: "healthy" | "degraded" | "unhealthy";
                                response_time_ms?: number;
                                error_message?: string | null;
                                /** Format: date-time */
                                last_success_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @description 대문자 스네이크 케이스 에러 코드
                 * @example VALIDATION_ERROR
                 */
                code: string;
                /** @example Request validation failed */
                message: string;
                details?: {
                    field?: string;
                    issue?: string;
                }[];
                /** Format: uuid */
                request_id: string;
            };
        };
        PaginatedEnvelope: {
            items?: unknown[];
            pagination?: {
                page?: number;
                page_size?: number;
                total_items?: number;
                total_pages?: number;
            };
        };
        AuthTokenResponse: {
            /** @description JWT */
            access_token?: string;
            /**
             * @default Bearer
             * @enum {string}
             */
            token_type: "Bearer";
            /** @description 초 단위. 환자 86400, 의료진 28800. */
            expires_in?: number;
        };
        /**
         * @description session — 주 1회 핵심 CBT 세션
         *     craving — 환자가 갈망 시 직접 진입
         *     resu   — 안전 분류기가 재발 감지 시 자동 전환
         *     soma   — 안전 분류기가 복약 중단 감지 시 자동 전환
         * @enum {string}
         */
        ConversationContext: "session" | "craving" | "resu" | "soma";
        /**
         * @description A=응급, B=비응급
         * @enum {string}
         */
        SafetyGrade: "A" | "B";
        /** @enum {string} */
        SafetyEventType: "suicide_risk" | "acute_intoxication" | "relapse" | "medication_stop" | "paws";
        NRSScore: number;
        PatientHomeResponse: {
            patient_id?: string;
            name?: string;
            sobriety_days?: number;
            current_week?: number;
            days_to_next_session?: number | null;
            today_tasks?: {
                checkin_pending?: boolean;
                session_today?: boolean;
            };
            /** Format: date */
            next_outpatient_date?: string | null;
            /** @description 백엔드의 LLM 잠금 상태 (환자 앱이 차단 UI 노출 여부 판단에 사용) */
            llm_locked?: boolean;
        };
        CheckinSubmit: {
            mood_nrs: components["schemas"]["NRSScore"];
            craving_nrs: components["schemas"]["NRSScore"];
            sleep_hours: number;
            medication_records: {
                medication_name?: string;
                taken?: boolean;
                side_effect_note?: string | null;
            }[];
            free_note?: string | null;
        };
        /** @description CheckinSubmit의 부분 수정. 모든 필드 optional. */
        CheckinPatch: {
            mood_nrs?: components["schemas"]["NRSScore"];
            craving_nrs?: components["schemas"]["NRSScore"];
            sleep_hours?: number;
            medication_records?: Record<string, never>[];
            free_note?: string | null;
        };
        Checkin: {
            checkin_id?: string;
            /** Format: date */
            date?: string;
            mood_nrs?: components["schemas"]["NRSScore"];
            craving_nrs?: components["schemas"]["NRSScore"];
            sleep_hours?: number;
            medication_records?: Record<string, never>[];
            free_note?: string | null;
            /** Format: date-time */
            submitted_at?: string;
        };
        CheckinResponse: {
            checkin?: components["schemas"]["Checkin"];
            safety_classification?: {
                grade?: components["schemas"]["SafetyGrade"];
                event_type?: components["schemas"]["SafetyEventType"];
                /** @enum {string} */
                next_action?: "llm_lock_p4" | "switch_resu" | "switch_soma" | "paws_resource" | "none";
            } | null;
        };
        Conversation: {
            conversation_id?: string;
            context?: components["schemas"]["ConversationContext"];
            session_id?: string | null;
            week_number?: number | null;
            /** Format: date-time */
            started_at?: string;
        };
        Message: {
            message_id?: string;
            conversation_id?: string;
            /** @enum {string} */
            role?: "user" | "assistant";
            text?: string;
            /** Format: date-time */
            created_at?: string;
        };
        CurrentSessionInfo: {
            active_conversation_id?: string | null;
            current_week?: number;
            /** Format: date */
            next_session_date?: string | null;
            llm_locked?: boolean;
        };
        SafetyEvent: {
            safety_event_id?: string;
            grade?: components["schemas"]["SafetyGrade"];
            event_type?: components["schemas"]["SafetyEventType"];
            /** Format: date-time */
            detected_at?: string;
            /** @enum {string} */
            source?: "conversation_message" | "checkin_free_note" | "conversation_pattern";
            /** @enum {string} */
            recommended_action?: "llm_lock_p4" | "switch_resu" | "switch_soma" | "paws_resource" | "none";
        };
        Settings: {
            /** @example 20:00 */
            daily_checkin_time?: string;
            session_day_of_week?: number;
            sso?: components["schemas"]["SupportPerson"];
        };
        SettingsPatch: {
            daily_checkin_time?: string;
            session_day_of_week?: number;
        };
        SupportPersonInput: {
            name: string;
            /** @enum {string} */
            relationship: "spouse" | "parent" | "sibling" | "child" | "friend" | "other";
            phone: string;
        };
        SupportPerson: components["schemas"]["SupportPersonInput"] & {
            sso_id?: string;
            /**
             * @description v3.0은 info_only만 사용. share_consent·full_account는 Post-MVP.
             * @enum {string}
             */
            access_level?: "info_only";
        };
        DischargeProfileInput: {
            name: string;
            phone: string;
            /** Format: date */
            date_of_birth: string;
            /** @enum {string} */
            sex: "male" | "female" | "other";
            /** Format: date */
            discharge_date: string;
            /**
             * @description DSM-5 중등도·중증
             * @enum {string}
             */
            diagnosis_severity: "moderate" | "severe";
            admission_days: number;
            medications: components["schemas"]["Medication"][];
            comorbidities?: ("depression" | "anxiety" | "insomnia" | "ptsd" | "bipolar" | "other")[];
            /** @enum {string} */
            suicide_ideation_history: "none" | "past" | "during_admission" | "current";
            primary_triggers: {
                /** @description 자유 텍스트 1~2줄. 백엔드 LLM이 정규화 태그로 변환. */
                raw_text: string;
            };
            sso: components["schemas"]["SupportPersonInput"];
            /** Format: date */
            next_outpatient_date: string;
        };
        Medication: {
            /**
             * @description naltrexone | acamprosate | disulfiram | other
             * @example naltrexone
             */
            name: string;
            /** @example 50mg */
            dose?: string;
            /** @example once_daily */
            frequency?: string;
            note?: string | null;
        };
        PatientListItem: {
            patient_id?: string;
            name?: string;
            current_week?: number;
            sobriety_days?: number;
            /** Format: date-time */
            last_active_at?: string | null;
            /** @enum {string} */
            program_status?: "active" | "completed" | "withdrawn";
            llm_locked?: boolean;
            unacknowledged_safety_events_count?: number;
        };
        PatientDetailDashboard: {
            patient_id?: string;
            /** @description D0 정보 요약 (병명·약물·SSO·다음 외래일) */
            discharge_profile?: Record<string, never>;
            progress?: {
                current_week?: number;
                sobriety_days?: number;
                /** Format: float */
                medication_adherence_rate_30d?: number;
            };
            recent_checkins_30d?: components["schemas"]["Checkin"][];
            active_session?: Record<string, never> | null;
            recent_sessions?: {
                session_id?: string;
                week_number?: number;
                /** Format: date-time */
                ended_at?: string;
                summary?: components["schemas"]["SessionSummary"];
            }[];
            /** @description v3.0에서 안전 이벤트 별도 조회·확인 처리 엔드포인트는 Post-MVP. 본 응답에 통합. */
            recent_safety_events?: {
                grade_a?: components["schemas"]["SafetyEvent"][];
                grade_b?: components["schemas"]["SafetyEvent"][];
            };
            llm_lock_status?: {
                locked?: boolean;
                /** Format: date-time */
                locked_at?: string | null;
                reason?: string | null;
            };
        };
        SafetyClassifyRequest: {
            patient_id: string;
            text: string;
            /** @enum {string} */
            source: "conversation_message" | "checkin_free_note" | "conversation_pattern";
            conversation_context?: components["schemas"]["ConversationContext"];
            /** @description 직전 맥락 2~5턴 */
            recent_dialogue?: {
                /** @enum {string} */
                role?: "user" | "assistant";
                text?: string;
            }[];
        };
        SafetyClassifyResponse: {
            classified?: boolean;
            /** @enum {string} */
            grade?: "A" | "B" | "none";
            /** @enum {string} */
            event_type?: "suicide_risk" | "acute_intoxication" | "relapse" | "medication_stop" | "paws" | "none";
            /** Format: float */
            confidence?: number;
            /** @enum {string} */
            matched_by?: "rule_keyword" | "llm_classifier" | "both" | "none";
            /** @description 등급 A·B인 경우 생성된 ID */
            safety_event_id?: string | null;
            /** @enum {string} */
            recommended_action?: "llm_lock_p4" | "switch_resu" | "switch_soma" | "paws_resource" | "none";
        };
        StageTrackRequest: {
            conversation_id: string;
            session_id: string;
            week_number: number;
            current_step: number;
            step_objectives?: string[];
            dialogue: Record<string, never>[];
        };
        StageTrackResponse: {
            current_step?: number;
            ready_to_advance?: boolean;
            /** Format: float */
            step_completion_estimate?: number;
            /** @enum {string} */
            step_drift_risk?: "low" | "medium" | "high";
            delivered_objectives?: string[];
            /** @enum {string} */
            recommended_next_action?: "advance_step" | "redirect_to_step_topic" | "continue_current";
        };
        SessionSummarizeRequest: {
            session_id: string;
            patient_id: string;
            week_number: number;
            full_dialogue: Record<string, never>[];
            session_objectives: string[];
            /** @description Week 1이면 null */
            previous_summary?: components["schemas"]["SessionSummary"] | null;
            patient_context?: Record<string, never>;
            /**
             * @description true면 202, false면 200
             * @default false
             */
            async: boolean;
        };
        /** @description 세션 요약기 출력. 다음 Week 세션 시작 시 시스템 프롬프트에 자동 주입. */
        SessionSummary: {
            session_completed_objectives?: string[];
            session_unaddressed_objectives?: string[];
            patient_key_insights?: string[];
            identified_triggers?: {
                /** @example work_stress */
                tag?: string;
                context?: string;
            }[];
            assigned_homework?: string;
            /** @enum {string} */
            emotional_tone?: "engaged" | "resistant" | "low" | "volatile" | "neutral";
            next_session_handoff_notes?: string;
            safety_flags?: {
                grade?: components["schemas"]["SafetyGrade"];
                event_type?: components["schemas"]["SafetyEventType"];
            }[];
            /** Format: date-time */
            generated_at?: string;
            /** @example claude-sonnet-4-6 */
            model_used?: string;
            generation_time_ms?: number;
        };
        OutputFilterResponse: {
            passed?: boolean;
            violations?: {
                /** @enum {string} */
                filter?: "medical_terminology" | "ave_violation";
                /** @enum {string} */
                severity?: "low" | "medium" | "high";
                matched_text?: string;
                reasoning?: string;
            }[];
            /** @enum {string} */
            recommended_action?: "allow" | "regenerate" | "fallback";
        };
        LLMInvokeRequest: {
            /** @enum {string} */
            model: "claude-opus-4-8" | "claude-opus-4-7" | "claude-sonnet-4-6" | "claude-haiku-4-5";
            /** @description Anthropic Messages 형식 */
            messages: Record<string, never>[];
            system?: string;
            max_tokens: number;
            /** Format: float */
            temperature?: number;
            /** @default false */
            stream: boolean;
            patient_id: string;
            /** @enum {string} */
            purpose: "patient_dialogue" | "safety_classification" | "stage_tracking" | "session_summarization" | "output_filtering" | "trigger_normalization";
            /** @enum {string} */
            caller_component: "orchestrator" | "safety_classifier" | "stage_tracker" | "session_summarizer" | "output_filter" | "trigger_normalizer";
        };
        /** @description stream=false 응답 */
        LLMInvokeResponse: {
            content?: string;
            usage?: {
                input_tokens?: number;
                output_tokens?: number;
            };
            stop_reason?: string;
            invocation_id?: string;
        };
    };
    responses: {
        /** @description 401 인증 실패 (토큰 만료·서명 오류) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 400 요청 검증 실패 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 404 리소스 없음 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
        PatientId: string;
        ConversationId: string;
        CheckinId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
